name: vega_embed_flutter
description:
  A Flutter widget to embed vega-lite charts to flutter web. Works well in Flutter web. 
  An experimental webview based widget is also exposed which can be used in mobile[WIP].

version: 0.7.0-null-safety

homepage: https://github.com/Abhilash-Chandran/vega_embed_flutter

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  web: ^1.0.0
  webview_flutter: ^4.4.4
  freezed_annotation: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  build_runner: ^2.4.8

flutter:
